name: Deploy Worker
on:
  push:
    branches:
      - main
  pull_request:
  repository_dispatch:
  # --- 新增的这一行 ---
  workflow_dispatch: # 允许从 GitHub UI 手动触发
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v4
      - name: Build & Deploy Worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
